# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4pIPR7GNRagmsUfBQtE_y0u5lli5nV-
"""

from sklearn import model_selection
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import joblib

x = np.array([[1],[2],[3],[4],[5],[6],[7],[8]])
y = np.array([40,45,50,60,65,70,75,85])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=3, random_state=1)

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("Actual Marks:", y_test)
print("Predicted Marks:", y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:",rmse)

print("R2 Score:",r2_score(y_test, y_pred))

joblib.dump(model, "model.pkl")