# -*- coding: utf-8 -*-
"""5th NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIWHji4vbUp7Suga0SprZ96Q54tDqtJ_
"""

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Sample text corpus
corpus = [
    "Natural language processing is fun",
    "Python is used for natural language processing",
    "Text vectorization is important for NLP"
]

# -------------------- Bag of Words --------------------
bow_vectorizer = CountVectorizer(lowercase=True)
bow_matrix = bow_vectorizer.fit_transform(corpus)

print("Bag of Words Feature Names:")
print(bow_vectorizer.get_feature_names_out())

print("\nBag of Words Feature Matrix:")
print(bow_matrix.toarray())

# -------------------- TF-IDF --------------------
tfidf_vectorizer = TfidfVectorizer(lowercase=True)
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus)

print("\nTF-IDF Feature Names:")
print(tfidf_vectorizer.get_feature_names_out())

print("\nTF-IDF Feature Matrix:")
print(tfidf_matrix.toarray())