# -*- coding: utf-8 -*-
"""6th NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zf0X_shhJtESUCFgdRa2KQhtUEs-jiiv
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk import pos_tag

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab')

sentence ="Natural Language Processing helps computers understand human"

tokens=word_tokenize(sentence)

tags = pos_tag(tokens)
print("POS Tags:",tags)