# -*- coding: utf-8 -*-
"""7 th NLP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIZNUmzc-cUyowH3jh3s29lCrRjFaIGu
"""

import nltk
from nltk import word_tokenize, pos_tag, ne_chunk
from nltk.tree import Tree

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('maxent_ne_chunker_tab') # Corrected: Download specific 'maxent_ne_chunker_tab'

text = "Apple Inc. was found by steve Jobs in Cupertino on April 1 1976"

token = word_tokenize(text)

pos_tags = pos_tag(token)

ner_tree = ne_chunk(pos_tags)

print("Named entities:\n")
for subtree in ner_tree:
    if isinstance(subtree, Tree):
      entity = " ".join([word for word, tag in subtree.leaves()])
      label = subtree.label()
      print(entity, "->", label)