# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_GWDfgj1uJTVmiwWfaxeZvI3F5lbopBS
"""

from textblob import TextBlob

reviews=[
    "I love this product, it is amazing!",
    "This is the worst purchase I never made.",
    "The product is okay, not great."
]

for review in reviews:
    blob=TextBlob(review)
    polarity = blob.sentiment.polarity
    if polarity > 0:
      sentiment = "Positive"
    elif polarity < 0:
      sentiment = "Negative"
    else:
       sentiment = "Neutral"
    print(f"Review: {review}\nSentiment: {sentiment}\nPolarity:{polarity}\n")